apiVersion: v1
kind: Service
metadata:
  name: {{ include "osa-suite.backendName" . }}
  labels:
    app.kubernetes.io/component: backend
    {{- include "osa-suite.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
