apiVersion: v1
kind: Service
metadata:
  name: {{ include "osa-suite.frontendName" . }}
  labels:
    app.kubernetes.io/component: frontend
    {{- include "osa-suite.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
